#!/bin/sh


# Cache dir
mkdir -p /var/cache/nginx

# Used to escape dollar sign in template
export DOLLAR='$'

envsubst < /etc/nginx/conf.d/default.conf.envsubst > /etc/nginx/sites-enabled/default

exec nginx